// This file is loaded ONLY by index.html

const weatherTypes = {
    sunny: { name: 'Sunny', imageSrc: 'images/sunny.png' },
    cloudy: { name: 'Cloudy', imageSrc: 'images/cloudy.png' },
    rainy: { name: 'Rainy', imageSrc: 'images/rain.png' },
    windy: { name: 'Windy', imageSrc: 'images/windy.png' }
};

const fishTypes = {
    largemouth: { name: 'Largemouth', imageSrc: 'images/largemouthbass.png' },
    smallmouth: { name: 'Smallmouth', imageSrc: 'images/smallmouthbass.png' },
    walleye: { name: 'Walleye', imageSrc: 'images/walleye.png' },
    perch: { name: 'Perch', imageSrc: 'images/perch.png' },
    pike: { name: 'Pike', imageSrc: 'images/pike.png' },
    muskie: { name: 'Muskie', imageSrc: 'images/muskie.png' },
    freshwaterdrum: { name: 'Freshwater Drum', imageSrc: 'images/freshwaterdrum.png' },
    crappie: { name: 'Crappie', imageSrc: 'images/crappie.png' },
    bluegill: { name: 'Bluegill', imageSrc: 'images/bluegill.png' },
    catfish: { name: 'Catfish', imageSrc: 'images/catfish.png' },
    rainbowtrout: { name: 'Rainbow Trout', imageSrc: 'images/rainbowtrout.png' },
    laketrout: { name: 'Lake Trout', imageSrc: 'images/laketrout.png' },
    brooktrout: { name: 'Brook Trout', imageSrc: 'images/brooktrout.png' },
    splake: { name: 'Splake', imageSrc: 'images/splake.png' },
    browntrout: { name: 'Brown Trout', imageSrc: 'images/browntrout.png' },
    chinooksalmon: { name: 'Chinook Salmon', imageSrc: 'images/chinooksalmon.png' },
    cohosalmon: { name: 'Coho Salmon', imageSrc: 'images/cohosalmon.png' },
    atlanticsalmon: { name: 'Atlantic Salmon', imageSrc: 'images/atlanticsalmon.png' },
    lakewhitefish: { name: 'Lake Whitefish', imageSrc: 'images/lakewhitefish.png' },
    carp: { name: 'Common Carp', imageSrc: 'images/carp.png' }
};

const clarityTypes = {
    clear: { name: 'Clear', imageSrc: 'images/clear.png' },
    muddy: { name: 'Muddy', imageSrc: 'images/muddy.png' }
};

const tempTypes = {
    cool: { name: 'Cool', imageSrc: 'images/cool.png' },
    warm: { name: 'Warm', imageSrc: 'images/warm.png' }
};

const colorMap = {
    'Green Pumpkin': { hex: '#4B5320', reason: 'The most versatile bass color. Perfectly mimics crawfish, gobies, and bluegill in most water clarities.' },
    'Watermelon': { hex: '#75A850', reason: 'A translucent, natural green that excels in clear water, mimicking small fish and other forage.' },
    'Bone White': { hex: '#F9F6EE', reason: 'A solid, highly visible color for topwater lures that provides a strong silhouette against the sky.' },
    'Crawfish': { hex: '#C84A33', reason: 'Directly imitates crawfish, a primary food source for bass in rocky environments, especially in spring.' },
    'Goby': { hex: '#967969', reason: 'Crucial in the Great Lakes region. It specifically imitates the round goby, a key forage species.' },
    'Sucker': { hex: '#BC8F8F', reason: 'Imitates suckers, a large, high-protein forage fish targeted by apex predators like pike and muskie.' },
    'Loon': { hex: '#333333', reason: 'A dark, solid color for large topwater lures that provides a strong silhouette against the sky, mimicking birds or small mammals.' },
    'Walleye': { hex: '#D4AF37', reason: 'In many northern lakes, walleye are a primary food source for giant muskie. This pattern imitates that forage.' },
    'Rainbow Trout': { hex: '#B5E6B5', reason: 'Mimics rainbow trout, a common food source for larger predators like lake trout and brown trout in stocked waters.' },
    'Smelt': { hex: '#A7B4B5', reason: 'A silvery, almost translucent pattern that imitates smelt, a key open-water baitfish for salmon and trout.' },
    'Hot Pink': { hex: '#FF69B4', reason: 'A bright, high-visibility color used in stained water for salmon and trout, thought to imitate the color of eggs or trigger an aggressive response.' },
    'Shock Pink': { hex: '#FC0FC0', reason: 'A bright, shocking color that stands out and is highly effective for crappie and other panfish, especially in stained water.' },
    'Carp Yellow': { hex: '#FFD700', reason: 'A classic carp color that perfectly mimics corn, one of their absolute favorite foods.' },
    'Hi-Vis Orange': { hex: '#FFA500', reason: 'A high-visibility color that stands out well against a variety of dark lake bottoms, making it easy for carp to find.' },
    'White': { hex: '#FFFFFF', reason: 'A highly visible color that effectively mimics the flash and profile of baitfish like shad, shiners, and ciscoes.' },
    'Chartreuse': { hex: '#DFFF00', reason: 'An extremely bright, high-visibility color that excels in stained, muddy, or deep water for nearly all species.' },
    'Black': { hex: '#000000', reason: 'Provides the strongest possible silhouette, making it effective in very muddy water and at night for all predators.' },
    'Blue': { hex: '#0000FF', reason: 'Often combined with black for jigs and spinnerbaits, it provides a subtle contrast that is highly effective in both clear and stained water.' },
    'Silver': { hex: '#C0C0C0', reason: 'Provides a realistic flash that mimics the scales of many common baitfish species like shiners and alewife.' },
    'Gold': { hex: '#FFD700', reason: 'Effective in stained or tannic water, imitating the flash of species like perch or golden shiners.' },
    'Perch': { hex: '#E8A317', reason: 'Directly imitates yellow perch, one of the most common and important forage fish in all of Ontario.' },
    'Firetiger': { hex: '#F3B700', reason: 'A classic, aggressive pattern with bright green, chartreuse, and orange that is highly effective in stained water for all predator species.' },
    'Natural Shad': { hex: '#B6C0C3', reason: 'A realistic color pattern that imitates common open-water baitfish like shad and shiners.' },
    'Chrome': { hex: '#E8E8E8', reason: 'Provides the maximum possible flash, making it excellent on sunny days for triggering reaction strikes from aggressive predators.' },
    'Red': { hex: '#FF0000', reason: 'Can trigger reaction strikes, imitate the color of gills on injured baitfish, or mimic the color of crawfish.' },
    'Orange': { hex: '#FFA500', reason: 'A high-visibility color that works well in stained water, particularly effective for salmon, trout, and walleye.' },
    'Yellow': { hex: '#FFFF00', reason: 'A bright, simple color that can be effective for panfish, walleye, and pike in stained water conditions.' },
    'Purple': { hex: '#800080', reason: 'A dark, subtle color that works well in low light and clear water as an alternative to black, especially for walleye and smallmouth.' },
    'Smoke': { hex: '#848884', reason: 'A subtle, translucent color that is very effective in ultra-clear water for wary smallmouth and lake trout.' },
    'Glow': { hex: '#E0FFD6', reason: 'Essential for deep water species like lake trout and salmon, as it remains visible where other colors fade to gray.' }
};

/**
 * This is the Lure Map SPECIFIC to the recommendations page.
 * It maps the specific recommendation strings (e.g., "Flipping Jig") to an image.
 */
const lureMap = {
    'Flipping Jig': { image: 'images/lures/flippingjig.png' },
    'Football Jig': { image: 'images/lures/footballjig.png' },
    'Drop Shot': { image: 'images/lures/dropshot.png' },
    'Topwater Popper': { image: 'images/lures/popper.png' },
    'Jerkbait': { image: 'images/lures/jerkbait.png' },
    'Large Jerkbaits': { image: 'images/lures/jerkbait.png' },
    'Small Jerkbaits': { image: 'images/lures/jerkbait.png' },
    'Ned Rig': { image: 'images/lures/nedrig.png' },
    'Big Jig': { image: 'images/lures/jig.png' },
    'Big Jigs': { image: 'images/lures/jig.png' },
    'Jig': { image: 'images/lures/jig.png' },
    'Jig with a Minnow': { image: 'images/lures/jigwithminnow.png' },
    'Jig and Minnow': { image: 'images/lures/jigwithminnow.png' },
    'Jig with Large Minnow': { image: 'images/lures/jigwithminnow.png' },
    'Jig and Worm': { image: 'images/lures/jigwithworm.png' },
    'Scented Jigs': { image: 'images/lures/jig.png' },
    'Bright Jigs with Scent': { image: 'images/lures/jig.png' },
    'Small Jigs': { image: 'images/lures/jig.png' },
    'Small Jig': { image: 'images/lures/jig.png' },
    'Bright Jigs': { image: 'images/lures/jig.png' },
    'Glow Jigs with Sucker Meat': { image: 'images/lures/jig.png' },
    'Glow Jigs with Bait': { image: 'images/lures/jig.png' },
    'Small Jig with Plastic': { image: 'images/lures/jig.png' },
    'Spinnerbait': { image: 'images/lures/spinnerbait.png' },
    'Big Spinnerbait': { image: 'images/lures/spinnerbait.png' },
    'Large Spinnerbaits': { image: 'images/lures/spinnerbait.png' },
    'Giant Spinnerbaits': { image: 'images/lures/spinnerbait.png' },
    'Small Spinners': { image: 'images/lures/inlinespinner.png' },
    'Small Spinner': { image: 'images/lures/inlinespinner.png' },
    'Inline Spinners': { image: 'images/lures/inlinespinner.png' },
    'Inline Spinner': { image: 'images/lures/inlinespinner.png' },
    'Small Inline Spinner': { image: 'images/lures/inlinespinner.png' },
    'Large Spinners': { image: 'images/lures/inlinespinner.png' },
    'Big Spinners': { image: 'images/lures/inlinespinner.png' },
    'Weighted Spinners': { image: 'images/lures/inlinespinner.png' },
    'Heavy Spinners': { image: 'images/lures/inlinespinner.png' },
    'Chatterbait': { image: 'images/lures/chatterbait.png' },
    'Chatterbaits': { image: 'images/lures/chatterbait.png' },
    'Lipless Crankbait': { image: 'images/lures/liplesscrank.png' },
    'Rattling Lipless Cranks': { image: 'images/lures/liplesscrank.png' },
    'Rattling Lipless Crankbait': { image: 'images/lures/liplesscrank.png' },
    'Swimbait': { image: 'images/lures/swimbait.png' },
    'Swimbaits': { image: 'images/lures/swimbait.png' },
    'Large Swimbaits': { image: 'images/lures/swimbait.png' },
    'Small Swimbaits': { image: 'images/lures/swimbait.png' },
    'Small Swimbait': { image: 'images/lures/swimbait.png' },
    'Senko Worm': { image: 'images/lures/senko.png' },
    'Spoon': { image: 'images/lures/spoon.png' },
    'Spoons': { image: 'images/lures/spoon.png' },
    'Small Spoons': { image: 'images/lures/spoon.png' },
    'Large Spoons': { image: 'images/lures/spoon.png' },
    'Trolling Spoons': { image: 'images/lures/spoon.png' },
    'Flutter Spoons': { image: 'images/lures/flutterspoon.png' },
    'Jigging Spoons': { image: 'images/lures/jiggingspoon.png' },
    'Small Jigging Spoon': { image: 'images/lures/jiggingspoon.png' },
    'Glow-in-the-Dark Spoons': { image: 'images/lures/spoon.png' },
    'Glow Spoons': { image: 'images/lures/spoon.png' },
    'Heavy Spoons with Rattles': { image: 'images/lures/spoon.png' },
    'Silver Spoon': { image: 'images/lures/spoon.png' },
    'Large Trolling Spoons': { image: 'images/lures/spoon.png' },
    'Tube Jig': { image: 'images/lures/tube.png' },
    'White Tube Jigs': { image: 'images/lures/tube.png' },
    'Heavy Tube Jigs': { image: 'images/lures/tube.png' },
    'Glow Tube Jigs': { image: 'images/lures/tube.png' },
    'Crappie Tubes': { image: 'images/lures/tube.png' },
    'Crankbait': { image: 'images/lures/crankbait.png' },
    'Giant Crankbaits': { image: 'images/lures/crankbait.png' },
    'Crawfish Crankbait': { image: 'images/lures/crankbait.png' },
    'Bright Crankbait': { image: 'images/lures/crankbait.png' },
    'Small Crankbait': { image: 'images/lures/crankbait.png' },
    'Rattling Crankbait': { image: 'images/lures/crankbait.png' },
    'Blade Bait': { image: 'images/lures/bladebait.png' },
    'Blade Baits': { image: 'images/lures/bladebait.png' },
    'Rattling Blade Bait': { image: 'images/lures/bladebait.png' },
    'A-Rig': { image: 'images/lures/arig.png' },
    'Topwater Spook': { image: 'images/lures/spook.png' },
    'Large Spooks': { image: 'images/lures/spook.png' },
    'Fluke': { image: 'images/lures/fluke.png' },
    'Creature Bait': { image: 'images/lures/creaturebait.png' },
    'Topwater Plopper': { image: 'images/lures/plopper.png' },
    'Whopper Ploppers': { image: 'images/lures/plopper.png' },
    'Bucktails': { image: 'images/lures/bucktail.png' },
    'Bucktail': { image: 'images/lures/bucktail.png' },
    'Large Bucktails ("Double 10s")': { image: 'images/lures/largebucktail.png' },
    'Glide Baits': { image: 'images/lures/glidebait.png' },
    'Glide Bait': { image: 'images/lures/glidebait.png' },
    'Large Glide Baits': { image: 'images/lures/glidebait.png' },
    'Bulldawg': { image: 'images/lures/bulldawg.png' },
    'Big Soft Plastics ("Bulldawg")': { image: 'images/lures/bulldawg.png' },
    'Big Soft Plastics': { image: 'images/lures/bulldawg.png' },
    'Live Worms': { image: 'images/lures/worm.png' },
    'Nightcrawlers': { image: 'images/lures/worm.png' },
    'Wax Worms': { image: 'images/lures/worm.png' },
    'Worms': { image: 'images/lures/worm.png' },
    'Scented Dough': { image: 'images/lures/powerbait.png' },
    'PowerBait': { image: 'images/lures/powerbait.png' },
    'Scented Dough Bait': { image: 'images/lures/powerbait.png' },
    'Scented Baits': { image: 'images/lures/powerbait.png' },
    'Live Minnows': { image: 'images/lures/minnow.png' },
    'Live Minnow': { image: 'images/lures/minnow.png' },
    'Crappie Minnows': { image: 'images/lures/minnow.png' },
    'Minnows': { image: 'images/lures/minnow.png' },
    'Small Minnows': { image: 'images/lures/minnow.png' },
    'Drop Shot with Minnow': { image: 'images/lures/dropshot.png' },
    'Slip Bobber with Minnow': { image: 'images/lures/slipbobber.png' },
    'Slip Bobber Rig': { image: 'images/lures/slipbobber.png' },
    'Live Minnow on a Jig': { image: 'images/lures/jigwithminnow.png' },
    'Live Minnow under a Bobber': { image: 'images/lures/slipbobber.png' },
    'Kastmasters': { image: 'images/lures/spoon.png' },
    'Large, Vibrating Lures': { image: 'images/lures/chatterbait.png' },
    'Vibrating Lures': { image: 'images/lures/chatterbait.png' },
    'Dodger/Flasher Rig': { image: 'images/lures/dodgerfly.png' },
    'Dodger and Fly/Spoon': { image: 'images/lures/dodgerfly.png' },
    'Bondy Bait': { image: 'images/lures/bondybait.png' },
    'Jigging Raps': { image: 'images/lures/jiggingrap.png' },
    'Jigging Rap': { image: 'images/lures/jiggingrap.png' },
    'Bottom Bouncer Rig': { image: 'images/lures/bottombouncer.png' },
    'Bottom Bouncer': { image: 'images/lures/bottombouncer.png' },
    'Lindy Rig': { image: 'images/lures/lindyrig.png' },
    'Rippin\' Rap': { image: 'images/lures/rippinrap.png' },
    'Slip Bobber with Leech': { image: 'images/lures/slipbobber.png' },
    'Large Minnow Lures': { image: 'images/lures/minnowlure.png' },
    'Noisy Topwater': { image: 'images/lures/noisytopwater.png' },
    'Extra Loud Topwater': { image: 'images/lures/noisytopwater.png' },
    'Topwater "Creeper"': { image: 'images/lures/creeper.png' },
    'Topwater Creeper': { image: 'images/lures/creeper.png' },
    'Beetle Spin': { image: 'images/lures/beetlespin.png' },
    'Beetle Spins': { image: 'images/lures/beetlespin.png' },
    'Cut Bait (Shad/Sucker)': { image: 'images/lures/cutbait.png' },
    'Cut Bait': { image: 'images/lures/cutbait.png' },
    'Live Bluegill/Perch': { image: 'images/lures/livebait.png' },
    'Live Bluegill': { image: 'images/lures/livebait.png' },
    'Chicken Livers': { image: 'images/lures/chickenliver.png' },
    'Stink Bait': { image: 'images/lures/stinkbait.png' },
    'Live Bait': { image: 'images/lures/livebait.png' },
    'Small Jigs under a Bobber': { image: 'images/lures/jig.png' },
    'Jig under a Bobber': { image: 'images/lures/slipbobber.png' },
    'Small Rattling Lures': { image: 'images/lures/liplesscrank.png' },
    'Scented Glow Jigs': { image: 'images/lures/jig.png' },
    'Boilies': { image: 'images/lures/boilies.png' },
    'Corn or Boilies on a Hair Rig': { image: 'images/lures/boilies.png' },
    'Bright Pop-up Boilie': { image: 'images/lures/boilies.png' },
    'Pack Bait': { image: 'images/lures/packbait.png' },
    'Pack Bait with Corn/Boilies': { image: 'images/lures/packbait.png' },
    'Method Feeder': { image: 'images/lures/methodfeeder.png' },
    'Method Feeder with Pack Bait': { image: 'images/lures/methodfeeder.png' },
    'Large Dough Ball': { image: 'images/lures/doughball.png' },
    'Dough Ball': { image: 'images/lures/doughball.png' },
    'Zig Rig': { image: 'images/lures/zigrig.png' },
    'Bread': { image: 'images/lures/bread.png' },
    'Bright Pop-up Corn': { image: 'images/lures/popupcorn.png' },
    'Pop-up Corn': { image: 'images/lures/popupcorn.png' },
    'Spawn Sacs': { image: 'images/lures/spawnsac.png' },
    'Frog': { image: 'images/lures/frog.png' },
    'Jigging Spoon': { image: 'images/lures/jiggingspoon.png' },
    'Squarebill Crankbait': { image: 'images/lures/squarebillcrankbait.png' }
};

const lureBaseMap = {
    'Large Jerkbaits': 'Jerkbait',
    'Small Jerkbaits': 'Jerkbait',
    'Flipping Jig': 'Jig',
    'Big Jig': 'Jig',
    'Big Jigs': 'Jig',
    'Football Jig': 'Jig',
    'Jig with a Minnow': 'Jig',
    'Jig and Minnow': 'Jig',
    'Jig with Large Minnow': 'Jig',
    'Jig and Worm': 'Jig',
    'Scented Jigs': 'Jig',
    'Bright Jigs with Scent': 'Jig',
    'Small Jigs': 'Jig',
    'Small Jig': 'Jig',
    'Bright Jigs': 'Jig',
    'Glow Jigs with Sucker Meat': 'Jig',
    'Glow Jigs with Bait': 'Jig',
    'Small Jig with Plastic': 'Jig',
    'Live Minnow on a Jig': 'Jig',
    'Small Jigs under a Bobber': 'Jig',
    'Jig under a Bobber': 'Jig',
    'Scented Glow Jigs': 'Jig',
    'Big Spinnerbait': 'Spinnerbait',
    'Large Spinnerbaits': 'Spinnerbait',
    'Giant Spinnerbaits': 'Spinnerbait',
    'Small Spinners': 'Inline Spinner',
    'Small Spinner': 'Inline Spinner',
    'Inline Spinners': 'Inline Spinner',
    'Small Inline Spinner': 'Inline Spinner',
    'Large Spinners': 'Inline Spinner',
    'Big Spinners': 'Inline Spinner',
    'Weighted Spinners': 'Inline Spinner',
    'Heavy Spinners': 'Inline Spinner',
    'Chatterbaits': 'Chatterbait',
    'Large, Vibrating Lures': 'Chatterbait',
    'Vibrating Lures': 'Chatterbait',
    'Rattling Lipless Cranks': 'Lipless Crankbait',
    'Rattling Lipless Crankbait': 'Lipless Crankbait',
    'Small Rattling Lures': 'Lipless Crankbait',
    'Swimbaits': 'Swimbait',
    'Large Swimbaits': 'Swimbait',
    'Small Swimbaits': 'Swimbait',
    'Small Swimbait': 'Swimbait',
    'Spoons': 'Spoon',
    'Small Spoons': 'Spoon',
    'Large Spoons': 'Spoon',
    'Trolling Spoons': 'Spoon',
    'Glow-in-the-Dark Spoons': 'Spoon',
    'Glow Spoons': 'Spoon',
    'Heavy Spoons with Rattles': 'Spoon',
    'Silver Spoon': 'Spoon',
    'Large Trolling Spoons': 'Spoon',
    'Kastmasters': 'Spoon',
    'White Tube Jigs': 'Tube Jig',
    'Heavy Tube Jigs': 'Tube Jig',
    'Glow Tube Jigs': 'Tube Jig',
    'Crappie Tubes': 'Tube Jig',
    'Giant Crankbaits': 'Crankbait',
    'Crawfish Crankbait': 'Crankbait',
    'Bright Crankbait': 'Crankbait',
    'Small Crankbait': 'Crankbait',
    'Rattling Crankbait': 'Crankbait',
    'Blade Baits': 'Blade Bait',
    'Rattling Blade Bait': 'Blade Bait',
    'Large Spooks': 'Topwater Spook',
    'Whopper Ploppers': 'Topwater Plopper',
    'Bucktails': 'Bucktail',
    'Large Bucktails ("Double 10s")': 'Bucktail',
    'Glide Baits': 'Glide Bait',
    'Large Glide Baits': 'Glide Bait',
    'Big Soft Plastics ("Bulldawg")': 'Bulldawg',
    'Big Soft Plastics': 'Bulldawg',
    'Nightcrawlers': 'Live Worms',
    'Wax Worms': 'Live Worms',
    'Worms': 'Live Worms',
    'PowerBait': 'Scented Dough Bait',
    'Scented Dough': 'Scented Dough Bait',
    'Scented Baits': 'Scented Dough Bait',
    'Live Minnows': 'Live Minnow',
    'Crappie Minnows': 'Live Minnow',
    'Minnows': 'Live Minnow',
    'Small Minnows': 'Live Minnow',
    'Drop Shot with Minnow': 'Drop Shot',
    'Slip Bobber with Minnow': 'Slip Bobber Rig',
    'Slip Bobber with Leech': 'Slip Bobber Rig',
    'Live Minnow under a Bobber': 'Slip Bobber Rig',
    'Dodger and Fly/Spoon': 'Dodger/Flasher Rig',
    'Jigging Raps': 'Jigging Rap',
    'Bottom Bouncer Rig': 'Bottom Bouncer',
    'Noisy Topwater': 'Extra Loud Topwater',
    'Topwater "Creeper"': 'Topwater Creeper',
    'Beetle Spins': 'Beetle Spin',
    'Cut Bait (Shad/Sucker)': 'Cut Bait',
    'Live Bluegill/Perch': 'Live Bluegill',
    'Corn or Boilies on a Hair Rig': 'Boilies',
    'Bright Pop-up Boilie': 'Boilies',
    'Pack Bait with Corn/Boilies': 'Pack Bait',
    'Method Feeder with Pack Bait': 'Method Feeder',
    'Large Dough Ball': 'Dough Ball',
    'Bright Pop-up Corn': 'Pop-up Corn',
    'Frog': 'Frog'
};